// DCCS/MSCoE Surgeon Operational Framework - Data Model
const FRAMEWORK = {
  title: "DCCS/MSCoE Surgeon Operational Design — 2027",
  hospital: "General Leonard Wood Community Hospital",
  hospitalAbbr: "GLWCH",
  installation: "Fort Leonard Wood",
  installationMission: "Force Generation — Basic Training, AIT, and NCOES for Engineers, Chemical, and Military Police",
  leader: { name: "LTC Matthew D. Holtkamp", title: "Deputy Commander for Clinical Services (DCCS) & MSCoE Command Surgeon", phone: "515-371-3630", email: "matthew.d.holtkamp.mil@health.mil" },
  assistant: { name: "SSG Flor Holloway", title: "NCOIC / Executive Assistant" },
  motto: "Work Smart, Move Fast, Be Nice",
  mission: "Continuously synchronize medical efforts across the GLWCH and MSCoE footprint to deliver the right care, at the right place, at the right time—building a medically ready force, developing a ready medical force, and achieving seamless MSCoE integration—in order to enable the MSCoE training mission.",
  vision: "Deliver reliable, high-quality healthcare that exceeds DHA standards for access and performance.",


  armyStrategy: {
    title: "Army Medicine Strategic Plan",
    introduction: "The Army Medicine Strategic Plan provides a comprehensive framework for Army Medicine to support the Army's warfighting mission and ensure the health and readiness of its Soldiers. Army Medicine will prioritize force protection, develop and implement effective tactics and procedures, foster a culture of excellence and innovation, ultimately ensuring that Army Medicine is trained and ready in support of Army's Mission, its Soldiers, and their Families. The plan focuses on five Lines of Effort with component objectives, optimizing Army Medicine's limited resources to enable the Army's success in current and future operational environments. As legacy organizations transferred to ACOMs, the focus has shifted to integration, convergence, advising, and enabling.",
    endState: "Army Health System that delivers a medically ready force and combat ready medical capabilities in support of Combatant Commanders while training Soldiers to sustain the warfighter for MDO, provide quality healthcare, and leverage the whole of government to fight and win our Nation's wars.",
    implementation: "The Army Medicine Strategic Plan is a multi-faceted approach nested in the Army's Continuous Transformation Campaign Plan. To accomplish objectives, we track both the achievement of outcomes and task execution. We measure success through Measures of Effectiveness (MOEs) and Measures of Performance (MOPs), including leadership development metrics, medical readiness rates, and alliance and partnership engagements. MOPs track efforts, while MOEs assess if efforts achieve desired impact. An assessment battle rhythm of accountability enables the Surgeon General to identify where integration, influence, and innovation are most needed.",
    loes: [
      { id: 1, category: "PEOPLE", color: "#795548", name: "Recruit, Build, & Strengthen the Army Medicine Profession", type: "Shaping (DSG)",
        description: "Army Medicine implements a 21st century talent management strategy, leveraging data-driven decision making to develop leaders and improve personnel outcomes. This approach integrates stakeholders to foster confident and competent leaders through continuous and deliberate training, education, and assessment. Additionally, Army Medicine will improve its recruiting and retention efforts by optimizing job satisfaction and financial compensation for healthcare professionals.",
        objectives: [
          { id: "1.1", name: "Man the Medical Force (Acquire)", description: "Army Medicine will mitigate ongoing recruitment and retention challenges to ensure a ready medical force. TSG is integrated with Army human resource enterprise to optimize recruiting, training, retention, and quality of life. Army Medicine will synchronize its efforts with Army initiatives to leverage human capital strategy, data analytics, and legislative reform to attract and retain top medical talent.", tasks: ["Develop and execute a national AMEDD Marketing Campaign to enhance recruiting platforms (websites, conventions, university/college visits)", "Manage medical accession programs to maintain health of the force standards", "Optimize incentive programs to attract and retain critical medical specialties"] },
          { id: "1.2", name: "Develop Leaders", description: "Train, Educate and Sustain Leaders. Army Medicine develops confident and competent leaders through progressive and sequential training, education, and experiential learning. Leaders are developed across all cohorts through institutional training, operational experience, and self-development.", tasks: ["Develop and implement leader development programs across all AMEDD cohorts", "Integrate leader competencies into professional military education", "Assess and refine leader development outcomes"] },
          { id: "1.3", name: "Modernize Human Capital Strategy", description: "Allocate People to Support Requirements. Army Medicine aligns talent management with force requirements, ensuring the right people are in the right positions to support the mission.", tasks: ["Align medical personnel distribution to meet operational requirements", "Leverage data analytics to optimize workforce planning", "Develop flexible manning models for emerging mission requirements"] },
          { id: "1.4", name: "Retain the Medical Force", description: "Retention of Total Army Healthcare Professionals. Army Medicine will execute retention strategies that address the unique needs of military healthcare professionals, including competitive compensation, career progression, and quality of life improvements.", tasks: ["Optimize special and incentive pays for medical professionals", "Develop career progression pathways for all AMEDD specialties", "Enhance quality of life programs for healthcare professionals and families"] }
        ],
        glwchConnection: "GLWCH recruits, develops, and retains healthcare professionals to staff the hospital and TOMS providers across MSCoE's three training brigades. Manning is critical — every unfilled provider slot directly impacts trainee care access." },
      { id: 2, category: "TRANSFORM", color: "#607D8B", name: "Transform Army Medicine for MDO & the Future Fight", type: "Shaping (MEDCoE CG)",
        description: "Army Medicine will transform to meet the demands of Multi-Domain Operations (MDO) and the future fight. This includes preparing for today's fight through transformation in contact, deliberate transformation for future fights, and concept-driven change to close gaps, mitigate risk, and support Large Scale Combat Operations (LSCO).",
        objectives: [
          { id: "2.1", name: "Transformation in Contact", description: "Prepare for Today's Fight. Army Medicine continuously adapts and improves its capabilities while conducting current operations, incorporating lessons learned and emerging technologies to maintain readiness.", tasks: ["Integrate lessons learned from current operations into medical doctrine", "Adapt medical capabilities to emerging threats and operational environments", "Implement rapid capability development for immediate operational needs"] },
          { id: "2.2", name: "Deliberate Transformation", description: "Prepare for the Future Fight — MDO Medical Formations at echelon. Army Medicine deliberately plans and executes transformation initiatives to align medical capabilities with the future operating environment.", tasks: ["Develop MDO-capable medical formations", "Design and test medical concepts for LSCO", "Integrate medical capabilities across all domains"] },
          { id: "2.3", name: "Concept Driven Change", description: "Rapidly Drive Change Translating Concepts to Capabilities to Close Gaps, Mitigate Risk, and Support LSCO. Army Medicine drives innovation through concept development, experimentation, and rapid prototyping.", tasks: ["Conduct medical experimentation during Army exercises", "Develop and test new medical concepts and technologies", "Translate validated concepts into fielded capabilities"] }
        ],
        glwchConnection: "GLWCH integrates AI clinical decision support (OpenEvidence, Ask Sage), automated readiness dashboards (Power BI), and telehealth to transform care delivery at a force generation installation." },
      { id: 3, category: "READINESS", color: "#4CAF50", name: "Sustain Health, Medically Preserve & Reconstitute Combat Power", type: "Decisive (DCG)",
        description: "This LOE focuses on sustaining the health of the force through integrated healthcare delivery, installation health service support, optimized Soldier medical readiness, and population health promotion. This is the primary LOE that GLWCH executes daily.",
        objectives: [
          { id: "3.1", name: "Integrate Across the MHS", description: "Healthcare Delivery, Readiness Services, Advocate with DHA. Army Medicine integrates across the Military Health System to ensure seamless healthcare delivery, advocate for readiness services, and coordinate with the Defense Health Agency.", tasks: ["Synchronize healthcare delivery across MTFs and civilian networks", "Advocate for readiness-focused healthcare policies with DHA", "Ensure continuity of care across the MHS enterprise"] },
          { id: "3.2", name: "Improve Installation Health Service Support", description: "Optimize Health Services and Force Health Protection on Installations. Army Medicine improves installation-level health services to support the force, ensuring facilities, programs, and services meet the needs of Soldiers and their Families.", tasks: ["Optimize installation medical capabilities and capacity", "Improve access to care and patient experience metrics", "Enhance force health protection programs at installations"] },
          { id: "3.3", name: "Optimize Soldier Medical Readiness", description: "Improve Soldier Medical Readiness. Army Medicine focuses on ensuring every Soldier is medically ready for worldwide deployment through proactive health assessments, preventive medicine, and readiness tracking.", tasks: ["Achieve and maintain Individual Medical Readiness (IMR) targets", "Implement proactive medical readiness programs", "Develop predictive medical readiness analytics"] },
          { id: "3.4", name: "Promote Population Health", description: "Improve Health and Combat Readiness. Army Medicine promotes the health of the total force through disease prevention, health promotion, and wellness programs that enhance combat readiness.", tasks: ["Implement evidence-based health promotion programs", "Reduce preventable disease and injury rates", "Integrate Holistic Health and Fitness (H2F) medical support"] }
        ],
        glwchConnection: "This is GLWCH's primary LOE. The DCCS operational framework directly executes LOE 3 — improving healthcare delivery, optimizing DHA metrics (access, HEDIS), and ensuring every trainee and Soldier is medically ready. The trainee care model (TOMS→CTMC→Hospital) is the installation-level implementation of 'right care, right place, right time.'" },
      { id: 4, category: "READINESS", color: "#FF9800", name: "Deliver Combat Ready Medical Force", type: "Decisive (OTSG, Policy & Force Integration)",
        description: "This LOE ensures that medical units have the requisite personnel, training, equipment, and supplies to support generation of medical ready forces for combat. It encompasses generating current readiness, strategic readiness, and participation in theater-level exercises.",
        objectives: [
          { id: "4.1", name: "Generate Current Readiness", description: "Unit Medical Capabilities to Conduct Wartime Mission — Competition, Crisis, Conflict. Assess units and identify any gaps that need to be addressed before exercises or deployments through operational assessments. Ensure medical units have the requisite personnel, training, equipment, and supplies.", tasks: ["Develop and provide medical readiness policies, systems, and reporting mechanisms to identify readiness lag measures and positively influence lead measures", "AMEDD generates sufficient current readiness to meet demands for assigned, allocated, and immediate response forces", "Review readiness reporting to assess risks associated with personnel, training, equipment status, and supply levels"] },
          { id: "4.2", name: "Generate Strategic Readiness", description: "Man, Train, Equip, and Medically Set Theaters to Project Capability and Capacity. Strategic readiness is the Army's ability to provide combatant commanders with trained and ready units that can meet the joint force's operational demands.", tasks: ["Integrate into the DoW and HQDA risk reporting mechanisms (Army Strategic Readiness Assessment, Annual Joint Assessment, Joint Medical Estimate)", "Assess CLVIII HQDA Centrally Managed Programs (MMRP, UDP, MCDM) Quarterly", "Assess medical field system equipment fill rates across the total force quarterly", "Assess SRC 08 readiness to meet OPLAN and TPFDD requirements", "Assess Army Prepositioned Stock (APS) readiness for SRC 08 sets"] },
          { id: "4.3", name: "Theater Level JF & Multinational Exercises", description: "Optimize Health Services and Force Health Protection. Army Medicine plays a crucial role in ensuring medical capabilities are effectively employed in theater-level, joint forces, and multinational exercises.", tasks: ["Assess, identify, and integrate opportunities within the Joint-Exercise Priority List (JEPL) and Army-Exercise Priority List (AEPL)", "Consolidate and distribute potential training and exercise opportunities across Army Medicine", "Conduct knowledge management of exercise plans, and lessons learned"] }
        ],
        glwchConnection: "GLWCH trains and readies medical forces that deploy worldwide. The MSCoE Surgeon synchronizes medical readiness across three training brigades, ensures TOMS providers maintain clinical skills, and standardizes medical support for training exercises." },
      { id: 5, category: "READINESS", color: "#9C27B0", name: "Strengthen Alliances & Partnerships", type: "Decisive (OTSG, Policy & Force Integration)",
        description: "Army Medicine leverages agreements as well as collaboration and coordinating mechanisms with military and civilian partners to meet strategic objectives. By strengthening relationships, Army Medicine builds trust, collaboration, and interoperability that enhances the ability to provide care on the battlefield, respond to emerging health threats, and develop novel medical response capabilities.",
        objectives: [
          { id: "5.1", name: "Execute Military-Civilian Partnerships", description: "Medical Skills Sustainment; Strengthen the Nation's Disaster Medical System. Army Medicine creates military-civilian partnerships (MCPs) with civilian trauma centers, pre-hospital EMS teams and other civilian organizations to build and maintain readiness of the medical force.", tasks: ["Develop overarching HQDA MCP policy", "Develop and maintain a central registry of Army MCPs", "Monitor and assess readiness outcomes of Army medical personnel training at MCPs", "Document factors that affect the establishment and/or effective operation of MCPs"] },
          { id: "5.2", name: "Conduct Medical Security Cooperation", description: "ASCC's Mil-Mil Combined Exercises, GHE, FMS Cases and Professional Medical Education. In support of CCMD theater priorities, the Army builds globally integrated military health service support.", tasks: ["Identify personnel across the Army with formal responsibility of coordinating and planning MSC/GHE activities", "Develop Army MSC/GHE policy and doctrine", "Develop Army competencies at each echelon for planning and conducting MSC/GHE", "Develop a GHE data governance for medical C2 integration, and lessons learned"] },
          { id: "5.3", name: "Support Army Role in Interagency Programs", description: "Facilitate Interagency Engagements and Manage Agreements. Army Medicine maintains relationships, develops interagency agreements, participates in interagency governance, and represents Army leadership in Interagency decision forums.", tasks: ["Develop Army NDMS and Army Medical Defense Support of Civil Authorities policy", "Formalize Army roles in Medical DSCA Capabilities Based Assessments, Joint publications, Army policies, and EXORDs", "Liaise and develop DoD and Interagency plans and policies", "Develop best practices and lessons learned from medical DSCA operations"] }
        ],
        glwchConnection: "GLWCH partners with civilian healthcare networks for specialty referrals and maintains DHA integration as a Defense Health Network - West facility." }
    ],
    enablingObjectives: [
      { id: 1, name: "Make Data-Based Decisions", description: "Successful execution enables Army Medicine to support the Army's data-centric transformation; leveraging data as a strategic asset to enhance combat readiness, anticipate strategic and operational requirements, and sustain the health of the force.", tasks: ["Cultivate a data-centric culture", "Design the system", "Develop decision advantage", "Employ enterprise advantage", "Leverage relationships to achieve success"], glwch: "Power BI dashboards, readiness trackers, and automated metrics drive all DCCS decisions." },
      { id: 2, name: "Optimize Resources for the Army", description: "Army Medicine professionals effectively manage funding through prioritizing, aligning, validating, and documenting requirements. Optimizing resources enables Army Medicine to be agile, responsive, and relevant in support of the Army.", tasks: ["Develop and sustain Army Medicine human resource common operating picture", "Align and advocate for Army Medicine priority requirements (Authorizations/FTEs/Funding)", "Document Army Medicine program requirements, capabilities, capacity and risk", "Effectively maximize and manage MEDCOM funding"], glwch: "Functional needs analysis, predictive medical logistics, and care ladder optimization." },
      { id: 3, name: "Align Form and Function", description: "Army Medicine will align form and function to support the Army and warfighters in a resource constrained environment.", tasks: ["Codify TSG Integrator Role", "Align structure to mission directive", "Fully implement theater medical commands", "Validate requirements through model/study"], glwch: "Reorganizing clinics, centralizing brigade medical assets, and aligning manning to mission." },
      { id: 4, name: "Force Generation", description: "The Surgeon General executes Title 10 training authorities through GME/GDE/Phase 2 Clinical Training Programs/LTHET/MEDCoE and Medical Education and Training Campus programs to generate Combat Ready Medical Forces.", tasks: ["Force generation tasks are incorporated in the five Lines of Effort"], glwch: "Fort Leonard Wood's sole mission — every GLWCH action enables trainee throughput." }
    ]
  },

  leadership: {
    philosophy: {
      beliefs: [
        { title: "Leaders remove friction", text: "If a process is broken or stupid, fix it. The DCCS seat is about clearing obstacles so people can do meaningful work." },
        { title: "Clarity out of Chaos", text: "In the absence of explicit higher-level guidance, it is our job to build the plan. My role is to provide you with clear intent, set clear goalposts, and facilitate open communication. We will cut away the crap: if a task doesn't serve our core mission or my explicit operational plan, we aren't doing it." },
        { title: "Be Brilliant at the Basics", text: "Focusing on the basics and driving innovation are not juxtaposed—they go hand-in-hand. We must use innovative solutions and critical thinking to make our fundamental tasks faster, more streamlined, and more efficient." },
        { title: "Innovate to Empower", text: "Nobody is coming to save us with more money or personnel. We must look across DOTMLPF and leverage AI, Power BI, and dashboards to pick up the slack. Data isn't here to be cold or to micromanage you—it's here to relieve the burden on our staff and help us make smarter decisions." },
        { title: "Authority doesn't matter without responsibility", text: "If you're in charge of something, own it. Own the metrics, own the mission, own your team." },
        { title: "Bad behavior is a leadership problem", text: "No tolerance for toxic leadership, bullying, or passive neglect. Address it head-on — privately and professionally." },
        { title: "Visibility matters", text: "Be out there — in clinics, at huddles, in meetings that matter. Not to micromanage, but to listen and understand." }
      ],
      expectations: ["Know your people", "Be brilliant at the basics", "Use technology to work smarter", "Build trust up and down the chain", "Be the leader you would want to work for"]
    },
    intent: {
      purpose: "Continuously synchronize medical efforts across the GLWCH and MSCoE footprint to deliver the right care, at the right place, at the right time in order to enable the MSCoE training mission.",
      keyTasks: [
        "Improve the quality, access, and volume of care across primary care, emergency medicine, mental and behavioral health, surgical services, and all DCCS service lines through DHA metrics, standards-driven execution, and metric-driven improvement.",
        "Train the care ladder: Medic → Nurse → Advanced Practice Provider (Nurse Practitioner and Physician Assistant) → Physician, ensuring every member of the team works at the highest level of their scope of practice.",
        "Leverage data and AI tools to drive clinical efficiency and decision making.",
        "Be brilliant at the basics: use innovation and initiative to improve core work, eliminate low-value tasks, streamline processes, and stop doing work that does not serve the mission."
      ],
      endState: "GLWCH is a highly reliable medical organization that exceeds DHA standards, staffed by empowered leaders who take absolute ownership of their mission, their metrics, and their people."
    },
    communication: {
      openDoor: "My door is always open, but I expect you to attempt to solve problems at your level first. Go across deputy lanes, talk to your peers, and exhaust your resources. If you must bring a problem to me, bring viable solutions with it. If you force me to solve your problem for you, you probably won't like the answer because it won't be yours. I need your buy-in and your critical thinking.",
      battleRhythm: "Tuesday 0900 DCCS Sync: This meeting is specifically for Chiefs, AOs, and NCOICs. While I will pass down top-level information, its primary purpose is a critical touchpoint to understand the roadblocks your clinics are facing. We will use this time to talk across clinic lines, share great ideas, and solve systemic problems collectively in the room."
    },
    evaluations: {
      groundRules: [
        { title: "Most Qualified is capped", text: "The Army caps Most Qualified at 49% for officers and 24% for enlisted NCOs, so not all strong performers will receive that mark." },
        { title: "No stair-stepping", text: "I will give the highest rating to the best Officer, NCO, or civilian leader, regardless of where you fall in relation to your promotion board." },
        { title: "Silence means you are on track", text: "Silence from me means you are at least performing at a Highly Qualified/Proficient level." },
        { title: "Top-block transition rule", text: "I do NOT give Most Qualified/top-block ratings to Soldiers who are leaving the Army." }
      ],
      ratingFocusAreas: [
        "My direct observations (clinical, operational, leadership)",
        "Rater input, if I am your Senior Rater",
        "Senior enlisted leader perspectives",
        "Feedback from peers, subordinates, and patients, both formal and informal",
        "Contributions to hospital priorities: readiness, quality, safety, access, modernization, and organizational improvement"
      ],
      highlyQualified: ["Delivers consistent, high-quality performance within mission and intent", "Communicates clearly with patients, peers, and leadership", "Works well with peers and develops subordinates", "Meets professional standards (PT, licensure, continuing education)", "Solves problems within their scope and coordinates effectively", "Synchronizes efforts across departments and units", "Enhances patient safety, access to care, and readiness"],
      mostQualified: ["Fully ready to operate at the next echelon now", "Anticipates and solves higher-level problems with executable solutions", "Drives innovation (integrates new technology and improves workflow)", "Coaches and inspires others, building high-performance teams", "Exceeds professional standards (AFT, clinical certifications, leadership education)", "Executes multiple high-visibility missions simultaneously", "Understands and aligns to the operational and strategic picture, connecting GLWCH to DHA and DA readiness", "Actively develops military and civilian medical leaders", "Expands scope of practice of self and others to the fullest extent allowed"],
      finalThought: "At GLWCH, we accomplish the mission, care for our people, and leave the organization better than we found it. Not everyone will receive Most Qualified, but everyone can - and must - pursue excellence. Ask yourself daily: What have I done to improve patient care, readiness, and this organization? Then act on it."
    },
    orgChart: {
      commander: "COL Angela Diebal-Lee",
      csm: "CSM Johnny Thompson",
      dccs: "LTC Matthew Holtkamp",
      dcn: "LTC Thomas Waters",
      dca: "LTC Dexter Lamar",
      dcr: "LTC Jasper"
    }
  }
};

// Export for use
if (typeof module !== 'undefined') module.exports = FRAMEWORK;
